import {
  app,
  BrowserWindow,
  Menu,
  Tray,
  globalShortcut,
  ipcMain,
  nativeImage,
  screen,
  shell,
} from "electron";
import { join } from "node:path";
import { copyFileSync, existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { config as loadEnv } from "dotenv";
import * as cognee from "@felixai/cognee-client";
import { analyzeScreen } from "@felixai/api-client";
import { captureScreenshot } from "./services/screenshot";
import { ensureCogneeRunning } from "./services/docker";
import {
  isOnboardingComplete,
  markOnboardingComplete,
  ONBOARDING_QUESTIONS,
} from "./services/onboarding";
import { parseUserCommand } from "./services/commands";
import { FELIX_RECALL_PROMPT } from "./prompts";
import type { AskPayload, AskResult, DatasetName } from "./types";

// Stable userData path in dev and packaged builds (%APPDATA%/FelixAI on Windows).
app.setName("FelixAI");

// Resolve .env — dev (apps/desktop/.env) or packaged (%APPDATA%/FelixAI/.env).
function loadFelixEnv(): void {
  const candidates = [
    join(app.getPath("userData"), ".env"),
    join(process.resourcesPath, ".env"),
    join(app.getAppPath(), ".env"),
    join(__dirname, "../../.env"),
    join(process.cwd(), "apps/desktop/.env"),
    join(process.cwd(), ".env"),
  ];

  for (const envPath of candidates) {
    if (existsSync(envPath)) {
      loadEnv({ path: envPath });
      if (process.env.COGNEE_URL || process.env.OPENROUTER_API_KEY) break;
    }
  }
}

function ensureUserEnvTemplate(): void {
  const userEnv = join(app.getPath("userData"), ".env");
  if (existsSync(userEnv)) return;

  const template = join(process.resourcesPath, ".env.example");
  if (existsSync(template)) {
    copyFileSync(template, userEnv);
    console.info("[felix] Created", userEnv, "— add your API keys and restart.");
  }
}

loadFelixEnv();

if (!process.env.OPENROUTER_API_KEY) {
  console.warn("[felix] OPENROUTER_API_KEY not found in apps/desktop/.env");
}

const HOTKEY = "CommandOrControl+Shift+Space";
const COMPACT_WIDTH = 700;
const COMPACT_HEIGHT = 440;
const SESSION_ID = randomUUID();
const IMPROVE_EVERY_N = 5;

function openRouterVisionModel(): string | undefined {
  const model = process.env.OPENROUTER_VISION_MODEL?.trim();
  return model || undefined;
}

let interactionCount = 0;
const datasetsTouched = new Set<DatasetName>(["main"]);

// Single instance only — a second launch would fight over the hotkey and cache.
const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
}

// 32x32 accent disc, generated by scripts/make-icon.mjs (kept inline so the
// tray never depends on a resolvable file path across dev/packaged builds).
const TRAY_ICON =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAiklEQVR4nO3XMQ7AIAgFUI/e4zn3Qu1qU4WAwv8DA6P5T00UWu93Q5Zn0aVUCGAMeJQyYSzhWvAK4gZ4g02Q6HAVkREuIlaA0+EjQgREhk8RGUcvXkX27n+nQAPIDP8gClCAAtAA4A8RDQD6GcG/Y4qGhKIlgzelFG35Ccj2YDJDQEYzCZM2nIbVCzzHIE2sRiaHAAAAAElFTkSuQmCC";

let tray: Tray | null = null;
let popup: BrowserWindow | null = null;
let lastScreenshot: string | null = null;
let lastScreenContext = "";
let isPopupVisible = false;

const rendererDevUrl = process.env["ELECTRON_RENDERER_URL"];

function createPopup(): BrowserWindow {
  const win = new BrowserWindow({
    width: COMPACT_WIDTH,
    height: COMPACT_HEIGHT,
    show: false,
    frame: false,
    transparent: true,
    resizable: true,
    skipTaskbar: true,
    alwaysOnTop: true,
    hasShadow: false,
    backgroundColor: "#00000000",
    webPreferences: {
      preload: join(__dirname, "../preload/index.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  win.setAlwaysOnTop(true, "screen-saver");

  if (rendererDevUrl) {
    void win.loadURL(rendererDevUrl);
  } else {
    void win.loadFile(join(__dirname, "../renderer/index.html"));
  }

  // Dismiss only via ESC (global shortcut, header button, or key in popup).
  win.webContents.on("before-input-event", (_e, input) => {
    if (input.type === "keyDown" && input.key === "Escape") hidePopup();
  });

  return win;
}

function centerWindow(win: BrowserWindow, width: number, height: number): void {
  win.setSize(width, height);
  win.center();
}

function expandWindow(): void {
  if (!popup || popup.isDestroyed()) return;
  const { workArea } = screen.getPrimaryDisplay();
  const width = Math.min(1000, workArea.width - 100);
  const height = Math.min(700, workArea.height - 100);
  centerWindow(popup, width, height);
}

function hidePopup(): void {
  if (!popup || popup.isDestroyed()) return;
  centerWindow(popup, COMPACT_WIDTH, COMPACT_HEIGHT);
  popup.hide();
  isPopupVisible = false;
  popup.webContents.send("vision:status", "idle");
}

function sendVisionStatus(status: "idle" | "analyzing" | "ready" | "failed"): void {
  popup?.webContents.send("vision:status", status);
}

/** OpenRouter vision on summon — screenshot stays in main, never sent to UI. */
async function analyzeScreenInBackground(): Promise<void> {
  const shot = lastScreenshot;
  const openrouterKey = process.env.OPENROUTER_API_KEY;

  if (!shot || !openrouterKey) {
    lastScreenContext = "";
    sendVisionStatus(shot ? "failed" : "idle");
    return;
  }

  sendVisionStatus("analyzing");
  try {
    lastScreenContext = await analyzeScreen({
      apiKey: openrouterKey,
      screenshotDataUrl: shot,
      model: openRouterVisionModel(),
    });
    sendVisionStatus("ready");
  } catch (err) {
    console.error("OpenRouter vision on summon failed", err);
    lastScreenContext = "";
    sendVisionStatus("failed");
  }
}

function notifyPopupShown(skipVision = false): void {
  if (!popup || popup.isDestroyed()) return;
  const notify = () => {
    popup?.webContents.send("popup:shown");
    if (!skipVision) void analyzeScreenInBackground();
  };
  if (popup.webContents.isLoading()) {
    popup.webContents.once("did-finish-load", notify);
  } else {
    notify();
  }
}

/** First hotkey opens onboarding (no screenshot). After that, normal summon. */
async function summon(): Promise<void> {
  if (!popup || popup.isDestroyed()) popup = createPopup();
  const win = popup;

  centerWindow(win, COMPACT_WIDTH, COMPACT_HEIGHT);
  win.show();
  win.focus();
  isPopupVisible = true;

  if (!isOnboardingComplete()) {
    lastScreenshot = null;
    lastScreenContext = "";
    sendVisionStatus("idle");
    notifyPopupShown(true);
    return;
  }

  lastScreenshot = await captureScreenshot();
  lastScreenContext = "";
  notifyPopupShown();
}

function registerHotkeys(): void {
  const registered = globalShortcut.register(HOTKEY, () => void summon());
  if (!registered) console.error("Failed to register global shortcut", HOTKEY);

  globalShortcut.register("Escape", () => {
    if (isPopupVisible) hidePopup();
  });
}

function createTray(): void {
  let icon = nativeImage.createFromDataURL(TRAY_ICON);
  if (icon.isEmpty()) icon = nativeImage.createEmpty();
  tray = new Tray(icon);
  tray.setToolTip("FelixAI — press Ctrl+Shift+Space");
  tray.setContextMenu(
    Menu.buildFromTemplate([
      { label: "Ask (Ctrl+Shift+Space)", click: () => void summon() },
      { type: "separator" },
      { label: "Quit FelixAI", click: () => app.quit() },
    ]),
  );
  tray.on("click", () => void summon());
}

/** Bridge session cache → permanent graph (background, never blocks UI). */
function runImprove(dataset: DatasetName = "main"): void {
  void cognee
    .improve({ dataset, sessionIds: [SESSION_ID] })
    .catch((err) => console.error("improve failed", err));
}

function maybeImproveAfterInteraction(dataset: DatasetName): void {
  datasetsTouched.add(dataset);
  interactionCount += 1;
  if (interactionCount % IMPROVE_EVERY_N === 0) runImprove(dataset);
}

function registerIpc(): void {
  ipcMain.handle("getOnboardingState", () => ({
    complete: isOnboardingComplete(),
    questions: ONBOARDING_QUESTIONS.map((q) => q.question),
  }));

  ipcMain.handle(
    "completeOnboarding",
    (
      _e,
      answers: string[],
    ): { ok: boolean; error?: string } => {
      if (answers.length !== ONBOARDING_QUESTIONS.length) {
        return { ok: false, error: "Please answer all questions" };
      }

      for (let i = 0; i < ONBOARDING_QUESTIONS.length; i++) {
        const entry = ONBOARDING_QUESTIONS[i];
        const answer = answers[i]?.trim();
        if (!entry || !answer) {
          return { ok: false, error: "Please answer all questions" };
        }
      }

      // Mark done immediately — Cognee writes run in background (no UI blocking).
      markOnboardingComplete();
      datasetsTouched.add("main");

      for (let i = 0; i < ONBOARDING_QUESTIONS.length; i++) {
        const entry = ONBOARDING_QUESTIONS[i]!;
        const answer = answers[i]!.trim();
        void cognee
          .rememberQA(
            {
              question: entry.question,
              answer,
              context: entry.rememberContext,
            },
            { dataset: "main", sessionId: SESSION_ID },
          )
          .catch((err) => console.error("onboarding remember failed", err));
      }

      void cognee
        .improve({ dataset: "main", sessionIds: [SESSION_ID] })
        .catch((err) => console.error("onboarding improve failed", err));

      return { ok: true };
    },
  );

  ipcMain.handle("ask", async (_e, payload: AskPayload): Promise<AskResult> => {
    if (!isOnboardingComplete()) {
      return {
        answer: "Complete the setup questions first, then ask about your screen.",
        usedMemory: false,
      };
    }
    const dataset: DatasetName = payload.dataset;
    const shot = lastScreenshot;
    const command = parseUserCommand(payload.question);

    if (command?.kind === "forget") {
      try {
        await cognee.forget(command.dataset);
        return {
          answer: `Forgot the ${command.dataset} dataset.`,
          usedMemory: false,
        };
      } catch (err) {
        return {
          answer: `Could not forget: ${(err as Error).message}`,
          usedMemory: false,
        };
      }
    }

    if (!shot) {
      return {
        answer: "No screenshot was captured for this query.",
        usedMemory: false,
      };
    }

    let screenContext = lastScreenContext;
    const openrouterKey = process.env.OPENROUTER_API_KEY;
    if (!screenContext && openrouterKey) {
      try {
        screenContext = await analyzeScreen({
          apiKey: openrouterKey,
          screenshotDataUrl: shot,
          model: openRouterVisionModel(),
        });
        lastScreenContext = screenContext;
      } catch (err) {
        console.error("OpenRouter vision failed", err);
      }
    }

    if (command?.kind === "remember") {
      const rememberContext =
        screenContext.slice(0, 2000) || "Explicit remember command";
      const answer = "Got it — I'll remember that.";

      void cognee
        .rememberQA(
          {
            question: payload.question,
            answer: command.note,
            context: rememberContext,
          },
          { dataset, sessionId: SESSION_ID },
        )
        .then((res) => {
          popup?.webContents.send("remember:done", { qaId: res.id });
          maybeImproveAfterInteraction(dataset);
        })
        .catch((err) => console.error("remember command failed", err));

      return { answer, usedMemory: false };
    }

    const recallQuery = cognee.buildRecallQuery(payload.question, screenContext);
    const cogneeUp = await cognee.health();

    let answer = "";
    let usedMemory = false;

    if (cogneeUp) {
      try {
        const recalled = await cognee.recall(recallQuery, {
          dataset,
          sessionId: SESSION_ID,
          scope: "auto",
          searchType: "GRAPH_COMPLETION",
          systemPrompt: FELIX_RECALL_PROMPT,
        });
        answer = recalled.text.trim();
        usedMemory = recalled.usedMemory;
      } catch (err) {
        console.error("recall failed", err);
      }
    }

    if (!answer) {
      answer = cognee.buildFallbackAnswer(screenContext, cogneeUp);
    }

    const rememberContext =
      screenContext.slice(0, 2000) || "Screen Q&A via FelixAI";

    void cognee
      .rememberQA(
        {
          question: payload.question,
          answer,
          context: rememberContext,
        },
        { dataset, sessionId: SESSION_ID },
      )
      .then((res) => {
        popup?.webContents.send("remember:done", { qaId: res.id });
        maybeImproveAfterInteraction(dataset);
      })
      .catch((err) => console.error("remember failed", err));

    return { answer, usedMemory };
  });

  ipcMain.handle(
    "feedback",
    async (_e, qaId: string, score: number, dataset: DatasetName) => {
      try {
        if (qaId) {
          void cognee
            .feedback(qaId, score, { dataset, sessionId: SESSION_ID })
            .catch((err) => console.error("feedback failed", err));
        }
        void cognee
          .improve({ dataset, sessionIds: [SESSION_ID] })
          .catch((err) => console.error("improve after feedback failed", err));
        return { ok: true };
      } catch (err) {
        return { ok: false, error: (err as Error).message };
      }
    },
  );

  ipcMain.handle("listMemory", async () => cognee.listDatasets());

  ipcMain.handle(
    "openMemoryGraph",
    async (
      _e,
      datasetId: string,
    ): Promise<{ ok: boolean; error?: string }> => {
      try {
        if (!datasetId || typeof datasetId !== "string") {
          return { ok: false, error: "No dataset selected." };
        }

        const up = await cognee.health();
        if (!up) {
          return {
            ok: false,
            error: "Cognee is offline. Start Docker, then try again.",
          };
        }

        const url = cognee.visualizeGraphUrl(datasetId);
        if (!/^https?:\/\//.test(url)) {
          return { ok: false, error: "Invalid graph URL." };
        }

        try {
          await shell.openExternal(url);
          return { ok: true };
        } catch {
          // Fallback: save HTML locally when the OS won't open localhost URLs.
          const html = await cognee.visualizeGraph(datasetId);
          const filePath = join(
            app.getPath("userData"),
            `graph-${datasetId.slice(0, 8)}.html`,
          );
          await writeFile(filePath, html, "utf8");
          const openErr = await shell.openPath(filePath);
          if (openErr) {
            return { ok: false, error: openErr };
          }
          return { ok: true };
        }
      } catch (err) {
        return { ok: false, error: (err as Error).message };
      }
    },
  );

  ipcMain.handle("forgetPrivate", async () => {
    try {
      await cognee.forget("private");
      return { ok: true };
    } catch (err) {
      return { ok: false, error: (err as Error).message };
    }
  });

  ipcMain.handle("getStatus", async () => ({
    cogneeUp: await cognee.health(),
    sessionId: SESSION_ID,
    onboardingComplete: isOnboardingComplete(),
  }));

  ipcMain.handle("getDeepgramKey", () => process.env.DEEPGRAM_API_KEY ?? "");

  ipcMain.handle("hidePopup", () => hidePopup());

  ipcMain.handle("expandWindow", () => {
    expandWindow();
  });

  ipcMain.handle("recaptureScreen", async () => {
    if (popup && !popup.isDestroyed() && popup.isVisible()) {
      popup.hide();
      await new Promise((r) => setTimeout(r, 350));
    }
    lastScreenshot = await captureScreenshot();
    lastScreenContext = "";
    if (popup && !popup.isDestroyed()) {
      popup.show();
      popup.focus();
      isPopupVisible = true;
    }
    await analyzeScreenInBackground();
  });
}

if (gotLock) {
  // If the user launches a second instance, focus/summon the existing one.
  app.on("second-instance", () => void summon());

  app.whenReady().then(() => {
    if (process.platform === "win32") {
      app.setAppUserModelId("com.felixai.companion");
    }

    ensureUserEnvTemplate();
    loadFelixEnv();

    void ensureCogneeRunning(process.env.COGNEE_REPO_PATH);

    registerIpc();
    popup = createPopup();
    centerWindow(popup, COMPACT_WIDTH, COMPACT_HEIGHT);
    createTray();
    registerHotkeys();
  });
}

app.on("will-quit", () => {
  globalShortcut.unregisterAll();
  // Final improve on quit — sync session → permanent graph for demo + real use.
  for (const dataset of datasetsTouched) runImprove(dataset);
});

// FelixAI stays in the tray — don't quit when the popup is hidden.
app.on("window-all-closed", () => {
  /* intentionally no-op */
});
