import {
  app,
  BrowserWindow,
  Menu,
  Tray,
  globalShortcut,
  ipcMain,
  nativeImage,
  screen,
} from "electron";
import { join } from "node:path";
import { existsSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { config as loadEnv } from "dotenv";
import * as cognee from "@jarvis/cognee-client";
import { analyzeScreen, askText, askVision } from "@jarvis/api-client";
import { captureScreenshot } from "./services/screenshot";
import { ensureCogneeRunning } from "./services/docker";
import type { AskPayload, AskResult, DatasetName } from "./types";

// Resolve apps/desktop/.env regardless of where the dev server was launched.
// app.getAppPath() points at apps/desktop; __dirname is out/main at runtime.
for (const envPath of [
  join(app.getAppPath(), ".env"),
  join(__dirname, "../../.env"),
  join(process.cwd(), "apps/desktop/.env"),
  join(process.cwd(), ".env"),
]) {
  if (existsSync(envPath)) {
    loadEnv({ path: envPath });
    if (process.env.OPENAI_API_KEY) break;
  }
}

if (!process.env.OPENAI_API_KEY) {
  console.warn("[felix] OPENAI_API_KEY not found in apps/desktop/.env");
}

const HOTKEY = "CommandOrControl+Shift+Space";
const SESSION_ID = randomUUID();
const IMPROVE_EVERY_N = 5;

let interactionCount = 0;
const datasetsTouched = new Set<DatasetName>(["main"]);

// Single instance only — a second launch would fight over the hotkey and cache.
const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
}

// 32x32 accent disc, generated by scripts/make-icon.mjs (kept inline so the
// tray never depends on a resolvable file path across dev/packaged builds).
const TRAY_ICON =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAiklEQVR4nO3XMQ7AIAgFUI/e4zn3Qu1qU4WAwv8DA6P5T00UWu93Q5Zn0aVUCGAMeJQyYSzhWvAK4gZ4g02Q6HAVkREuIlaA0+EjQgREhk8RGUcvXkX27n+nQAPIDP8gClCAAtAA4A8RDQD6GcG/Y4qGhKIlgzelFG35Ccj2YDJDQEYzCZM2nIbVCzzHIE2sRiaHAAAAAElFTkSuQmCC";

let tray: Tray | null = null;
let popup: BrowserWindow | null = null;
let lastScreenshot: string | null = null;

const rendererDevUrl = process.env["ELECTRON_RENDERER_URL"];

function createPopup(): BrowserWindow {
  const win = new BrowserWindow({
    width: 440,
    height: 560,
    show: false,
    frame: false,
    resizable: false,
    skipTaskbar: true,
    alwaysOnTop: true,
    // Windows 11 frosted-glass. backgroundColor with alpha lets the material show.
    backgroundColor: "#00000000",
    backgroundMaterial: "acrylic",
    webPreferences: {
      preload: join(__dirname, "../preload/index.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  win.setAlwaysOnTop(true, "screen-saver");

  if (rendererDevUrl) {
    void win.loadURL(rendererDevUrl);
  } else {
    void win.loadFile(join(__dirname, "../renderer/index.html"));
  }

  win.on("blur", () => {
    if (win.webContents.isDevToolsOpened()) return;
    win.hide();
  });

  // Escape dismisses the popup (Spotlight-style). Handled in main so it works
  // regardless of which renderer element has focus.
  win.webContents.on("before-input-event", (_e, input) => {
    if (input.type === "keyDown" && input.key === "Escape") win.hide();
  });

  return win;
}

function positionNearCursor(win: BrowserWindow): void {
  const cursor = screen.getCursorScreenPoint();
  const area = screen.getDisplayNearestPoint(cursor).workArea;
  const [w, h] = win.getSize();
  let x = cursor.x + 8;
  let y = cursor.y + 8;
  if (x + w > area.x + area.width) x = area.x + area.width - w - 8;
  if (y + h > area.y + area.height) y = area.y + area.height - h - 8;
  if (x < area.x) x = area.x + 8;
  if (y < area.y) y = area.y + 8;
  win.setPosition(Math.round(x), Math.round(y));
}

/** The core summon: capture screenshot FIRST (F2), then show the popup (F1). */
async function summon(): Promise<void> {
  lastScreenshot = await captureScreenshot();

  if (!popup || popup.isDestroyed()) popup = createPopup();
  const win = popup;

  positionNearCursor(win);
  win.show();
  win.focus();

  // Push the fresh screenshot and signal a new summon so the renderer can
  // re-focus its input (autoFocus only fires on first mount, not on re-show).
  const notify = () => {
    win.webContents.send("screenshot:captured", lastScreenshot);
    win.webContents.send("popup:shown");
  };
  if (win.webContents.isLoading()) {
    win.webContents.once("did-finish-load", notify);
  } else {
    notify();
  }
}

function createTray(): void {
  let icon = nativeImage.createFromDataURL(TRAY_ICON);
  if (icon.isEmpty()) icon = nativeImage.createEmpty();
  tray = new Tray(icon);
  tray.setToolTip("FelixAI — press Ctrl+Shift+Space");
  tray.setContextMenu(
    Menu.buildFromTemplate([
      { label: "Ask (Ctrl+Shift+Space)", click: () => void summon() },
      { type: "separator" },
      { label: "Quit FelixAI", click: () => app.quit() },
    ]),
  );
  tray.on("click", () => void summon());
}

/** Bridge session cache → permanent graph (background, never blocks UI). */
function runImprove(dataset: DatasetName = "main"): void {
  void cognee
    .improve({ dataset, sessionIds: [SESSION_ID] })
    .catch((err) => console.error("improve failed", err));
}

function maybeImproveAfterInteraction(dataset: DatasetName): void {
  datasetsTouched.add(dataset);
  interactionCount += 1;
  if (interactionCount % IMPROVE_EVERY_N === 0) runImprove(dataset);
}

function registerIpc(): void {
  ipcMain.handle("ask", async (_e, payload: AskPayload): Promise<AskResult> => {
    const dataset: DatasetName = payload.dataset;
    const shot = lastScreenshot;

    // Session recall first, so the answer can build on this sitting's context.
    let memory = "";
    try {
      memory = await cognee.recall(payload.question, {
        dataset,
        sessionId: SESSION_ID,
        scope: "session",
      });
    } catch (err) {
      console.error("recall failed", err);
    }

    if (!process.env.OPENAI_API_KEY) {
      return {
        answer:
          "No OPENAI_API_KEY set. Add it to apps/desktop/.env and restart FelixAI.",
        usedMemory: Boolean(memory),
      };
    }
    if (!shot) {
      return {
        answer: "No screenshot was captured for this query.",
        usedMemory: false,
      };
    }

    let screenContext = "";
    const openrouterKey = process.env.OPENROUTER_API_KEY;
    if (openrouterKey) {
      try {
        screenContext = await analyzeScreen({
          apiKey: openrouterKey,
          screenshotDataUrl: shot,
        });
      } catch (err) {
        console.error("OpenRouter vision failed, falling back to OpenAI", err);
      }
    }

    let answer: string;
    try {
      if (screenContext) {
        answer = await askText({
          apiKey: process.env.OPENAI_API_KEY,
          question: payload.question,
          screenContext,
          memoryContext: memory,
        });
      } else {
        answer = await askVision({
          apiKey: process.env.OPENAI_API_KEY,
          question: payload.question,
          screenshotDataUrl: shot,
          memoryContext: memory,
        });
      }
    } catch (err) {
      return {
        answer: `AI error: ${(err as Error).message}`,
        usedMemory: Boolean(memory),
      };
    }

    const rememberContext =
      screenContext.slice(0, 2000) || "Screen Q&A via FelixAI";

    void cognee
      .rememberQA(
        {
          question: payload.question,
          answer,
          context: rememberContext,
        },
        { dataset, sessionId: SESSION_ID },
      )
      .then((res) => {
        popup?.webContents.send("remember:done", { qaId: res.id });
        maybeImproveAfterInteraction(dataset);
      })
      .catch((err) => console.error("remember failed", err));

    return { answer, usedMemory: Boolean(memory) };
  });

  ipcMain.handle(
    "feedback",
    async (_e, qaId: string, score: number, dataset: DatasetName) => {
      try {
        if (qaId) {
          await cognee.feedback(qaId, score, { dataset, sessionId: SESSION_ID });
        }
        await cognee.improve({ dataset, sessionIds: [SESSION_ID] });
        return { ok: true };
      } catch (err) {
        return { ok: false, error: (err as Error).message };
      }
    },
  );

  ipcMain.handle("listMemory", async () => cognee.listDatasets());

  ipcMain.handle("forgetPrivate", async () => {
    try {
      await cognee.forget("private");
      return { ok: true };
    } catch (err) {
      return { ok: false, error: (err as Error).message };
    }
  });

  ipcMain.handle("getStatus", async () => ({
    cogneeUp: await cognee.health(),
    sessionId: SESSION_ID,
  }));

  ipcMain.handle("hidePopup", () => popup?.hide());
}

if (gotLock) {
  // If the user launches a second instance, focus/summon the existing one.
  app.on("second-instance", () => void summon());

  app.whenReady().then(() => {
    if (process.platform === "win32") {
      app.setAppUserModelId("com.felixai.companion");
    }

    void ensureCogneeRunning(process.env.COGNEE_REPO_PATH);

    registerIpc();
    popup = createPopup();
    createTray();

    const registered = globalShortcut.register(HOTKEY, () => void summon());
    if (!registered)
      console.error("Failed to register global shortcut", HOTKEY);
  });
}

app.on("will-quit", () => {
  globalShortcut.unregisterAll();
  // Final improve on quit — sync session → permanent graph for demo + real use.
  for (const dataset of datasetsTouched) runImprove(dataset);
});

// FelixAI stays in the tray — don't quit when the popup is hidden.
app.on("window-all-closed", () => {
  /* intentionally no-op */
});
