import {
  app,
  BrowserWindow,
  Menu,
  Tray,
  globalShortcut,
  ipcMain,
  nativeImage,
  screen,
} from "electron";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { config as loadEnv } from "dotenv";
import * as cognee from "@jarvis/cognee-client";
import { askVision } from "@jarvis/api-client";
import { captureScreenshot } from "./services/screenshot";
import { ensureCogneeRunning } from "./services/docker";
import type { AskPayload, AskResult, DatasetName } from "./types";

loadEnv();

const HOTKEY = "CommandOrControl+Shift+Space";
const SESSION_ID = randomUUID();

// 32x32 accent disc, generated by scripts/make-icon.mjs (kept inline so the
// tray never depends on a resolvable file path across dev/packaged builds).
const TRAY_ICON =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAiklEQVR4nO3XMQ7AIAgFUA/ao3Toze1qU4WAwv8DA6P5T00U2n31hizPokepEMAY0JUyYSzhWvAK4gZ4g02Q6HAVkREuIlaA0+EjQgREhk8RGUcvXkX27n+nQAPIDP8gClCAAtAA4A8RDQD6GcG/Y4qGhKIlgzelFG35Ccj2YDJDQEYzCZM2nIbVC3ve9CDMQQLFAAAAAElFTkSuQmCC";

let tray: Tray | null = null;
let popup: BrowserWindow | null = null;
let lastScreenshot: string | null = null;

const rendererDevUrl = process.env["ELECTRON_RENDERER_URL"];

function createPopup(): BrowserWindow {
  const win = new BrowserWindow({
    width: 440,
    height: 560,
    show: false,
    frame: false,
    resizable: false,
    skipTaskbar: true,
    alwaysOnTop: true,
    // Windows 11 frosted-glass. backgroundColor with alpha lets the material show.
    backgroundColor: "#00000000",
    backgroundMaterial: "acrylic",
    webPreferences: {
      preload: join(__dirname, "../preload/index.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  win.setAlwaysOnTop(true, "screen-saver");

  if (rendererDevUrl) {
    void win.loadURL(rendererDevUrl);
  } else {
    void win.loadFile(join(__dirname, "../renderer/index.html"));
  }

  win.on("blur", () => {
    if (win.webContents.isDevToolsOpened()) return;
    win.hide();
  });

  return win;
}

function positionNearCursor(win: BrowserWindow): void {
  const cursor = screen.getCursorScreenPoint();
  const area = screen.getDisplayNearestPoint(cursor).workArea;
  const [w, h] = win.getSize();
  let x = cursor.x + 8;
  let y = cursor.y + 8;
  if (x + w > area.x + area.width) x = area.x + area.width - w - 8;
  if (y + h > area.y + area.height) y = area.y + area.height - h - 8;
  if (x < area.x) x = area.x + 8;
  if (y < area.y) y = area.y + 8;
  win.setPosition(Math.round(x), Math.round(y));
}

/** The core summon: capture screenshot FIRST (F2), then show the popup (F1). */
async function summon(): Promise<void> {
  lastScreenshot = await captureScreenshot();

  if (!popup || popup.isDestroyed()) popup = createPopup();
  const win = popup;

  positionNearCursor(win);
  win.show();
  win.focus();

  const send = () =>
    win.webContents.send("screenshot:captured", lastScreenshot);
  if (win.webContents.isLoading()) {
    win.webContents.once("did-finish-load", send);
  } else {
    send();
  }
}

function createTray(): void {
  let icon = nativeImage.createFromDataURL(TRAY_ICON);
  if (icon.isEmpty()) icon = nativeImage.createEmpty();
  tray = new Tray(icon);
  tray.setToolTip("Jarvis — press Ctrl+Shift+Space");
  tray.setContextMenu(
    Menu.buildFromTemplate([
      { label: "Ask (Ctrl+Shift+Space)", click: () => void summon() },
      { type: "separator" },
      { label: "Quit Jarvis", click: () => app.quit() },
    ]),
  );
  tray.on("click", () => void summon());
}

function registerIpc(): void {
  ipcMain.handle("ask", async (_e, payload: AskPayload): Promise<AskResult> => {
    const dataset: DatasetName = payload.dataset;
    const shot = lastScreenshot;

    // F4 — recall relevant past context first.
    let memory = "";
    try {
      memory = await cognee.recall(payload.question, {
        dataset,
        sessionId: SESSION_ID,
      });
    } catch (err) {
      console.error("recall failed", err);
    }

    if (!process.env.OPENAI_API_KEY) {
      return {
        answer:
          "No OPENAI_API_KEY set yet. Add it to apps/desktop/.env and restart Jarvis to enable answers.",
        usedMemory: Boolean(memory),
      };
    }
    if (!shot) {
      return {
        answer: "No screenshot was captured for this query.",
        usedMemory: false,
      };
    }

    // F4 — vision answer using screenshot + recalled memory.
    let answer: string;
    try {
      answer = await askVision({
        apiKey: process.env.OPENAI_API_KEY,
        question: payload.question,
        screenshotDataUrl: shot,
        memoryContext: memory,
      });
    } catch (err) {
      return {
        answer: `Vision error: ${(err as Error).message}`,
        usedMemory: Boolean(memory),
      };
    }

    // F5 — remember in the BACKGROUND. cognify is slow (30–120s); never block UI.
    void cognee
      .rememberQA(
        {
          question: payload.question,
          answer,
          context: "Screen Q&A via Jarvis",
        },
        { dataset, sessionId: SESSION_ID },
      )
      .then((res) =>
        popup?.webContents.send("remember:done", { qaId: res.id }),
      )
      .catch((err) => console.error("remember failed", err));

    return { answer, usedMemory: Boolean(memory) };
  });

  // F8 — feedback → improve.
  ipcMain.handle(
    "feedback",
    async (_e, qaId: string, score: number, dataset: DatasetName) => {
      try {
        if (qaId) {
          await cognee.feedback(qaId, score, { dataset, sessionId: SESSION_ID });
        }
        await cognee.improve({ dataset, sessionIds: [SESSION_ID] });
        return { ok: true };
      } catch (err) {
        return { ok: false, error: (err as Error).message };
      }
    },
  );

  // F6 — memory view.
  ipcMain.handle("listMemory", async () => cognee.listDatasets());

  // F7 — forget private dataset.
  ipcMain.handle("forgetPrivate", async () => {
    try {
      await cognee.forget("private");
      return { ok: true };
    } catch (err) {
      return { ok: false, error: (err as Error).message };
    }
  });

  ipcMain.handle("getStatus", async () => ({
    cogneeUp: await cognee.health(),
    sessionId: SESSION_ID,
  }));

  ipcMain.handle("hidePopup", () => popup?.hide());
}

app.whenReady().then(() => {
  if (process.platform === "win32") {
    app.setAppUserModelId("com.jarvis.companion");
  }

  void ensureCogneeRunning(process.env.COGNEE_REPO_PATH);

  registerIpc();
  popup = createPopup();
  createTray();

  const registered = globalShortcut.register(HOTKEY, () => void summon());
  if (!registered) console.error("Failed to register global shortcut", HOTKEY);
});

app.on("will-quit", () => globalShortcut.unregisterAll());

// Jarvis lives in the tray — don't quit when the popup is hidden/closed.
app.on("window-all-closed", () => {
  /* intentionally no-op */
});
